github: [AXI0MH1VE]
patreon: # Replace with Patreon URL
open_collective: # Replace with Open Collective URL
ko_fi: # Replace with Ko-fi URL
tidelift: # Replace with Tidelift URL
community_bridge: # Replace with Community Bridge URL
liberapay: # Replace with Liberapay URL
issuehunt: # Replace with IssueHunt URL
otechie: # Replace with Otechie URL
lfx_crowdfunding: # Replace with LFX Crowdfunding URL
polar: # Replace with Polar URL
buy_me_a_coffee: AXI0MH1VE
custom: ["https://www.paypal.com/paypalme/yourname"]
